# Generated by Django 4.0.4 on 2022-05-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='job',
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.type'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
