# Generated by Django 4.0.4 on 2022-05-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='type',
        ),
        migrations.AddField(
            model_name='skills',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.type'),
            preserve_default=False,
        ),
    ]
